project:
  type: website

website:
  title: "Wine Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: models.qmd
        text: Model
      - Sources.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



